apiVersion: v1
kind: Service
metadata:
  name: {{ include "relay-forge.fullname" . }}-api
  labels:
    {{- include "relay-forge.labels" . | nindent 4 }}
    {{- include "relay-forge.selectorLabels" (dict "component" "api" "root" .) | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    {{- include "relay-forge.selectorLabels" (dict "component" "api" "root" .) | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.global.metrics.port }}
      targetPort: metrics
      protocol: TCP
