import React, { useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { Button, Input } from '@relayforge/ui';
import { useApi } from '@/hooks/useApi';
import { ServerConnectionModal } from '@/components/ServerConnectionModal';

const relayForgeIconSrc = '/branding/relay-forge-icon.png';

export function ResetPasswordPage() {
  const api = useApi();
  const [searchParams] = useSearchParams();
  const initialToken = useMemo(() => searchParams.get('token') ?? '', [searchParams]);
  const [token, setToken] = useState(initialToken);
  const [newPassword, setNewPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [connectionsOpen, setConnectionsOpen] = useState(false);

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    setError(null);
    setSuccess(null);

    if (!token.trim()) {
      setError('Enter the reset token generated by your server.');
      return;
    }

    if (newPassword !== confirmPassword) {
      setError('Passwords do not match.');
      return;
    }

    if (newPassword.length < 8) {
      setError('Password must be at least 8 characters.');
      return;
    }

    setLoading(true);
    try {
      await api.confirmPasswordReset({ token: token.trim(), newPassword });
      setSuccess('Your password has been reset. You can sign in with the new password now.');
      setNewPassword('');
      setConfirmPassword('');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not reset the password.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="auth-shell flex min-h-screen items-center justify-center overflow-hidden px-4">
      <div className="pointer-events-none absolute inset-0">
        <div className="animate-soft-float absolute left-[12%] top-[16%] h-40 w-40 rounded-full bg-[rgba(var(--rf-accent),0.12)] blur-3xl" />
        <div className="animate-soft-float absolute bottom-[14%] right-[10%] h-52 w-52 rounded-full bg-[rgba(56,189,248,0.10)] blur-3xl [animation-delay:800ms]" />
      </div>

      <div className="relative z-10 w-full max-w-md">
        <div className="rf-floating-shell animate-fade-scale rounded-[36px] p-8">
          <div className="mb-8 text-center">
            <img
              src={relayForgeIconSrc}
              alt="RelayForge"
              className="mx-auto mb-5 h-20 w-20 rounded-[28px] border border-black/5 bg-white object-cover shadow-[0_18px_40px_rgba(15,23,42,0.12)]"
            />
            <p className="text-text-secondary text-[11px] font-semibold uppercase tracking-[0.28em]">
              RelayForge
            </p>
            <h1 className="text-text-primary mt-3 text-[34px] font-semibold tracking-[-0.05em]">
              Choose a new password
            </h1>
          </div>

          <form onSubmit={handleSubmit} className="space-y-5">
            {error && (
              <div className="rounded-2xl border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-500">
                {error}
              </div>
            )}

            {success && (
              <div className="rounded-2xl border border-emerald-500/20 bg-emerald-500/10 px-4 py-3 text-sm text-emerald-600">
                {success}
              </div>
            )}

            <Input
              label="Reset token"
              name="token"
              value={token}
              onChange={(event) => setToken(event.target.value)}
              required
              autoComplete="one-time-code"
            />

            <Input
              label="New password"
              name="newPassword"
              type="password"
              value={newPassword}
              onChange={(event) => setNewPassword(event.target.value)}
              required
              autoComplete="new-password"
            />

            <Input
              label="Confirm new password"
              name="confirmPassword"
              type="password"
              value={confirmPassword}
              onChange={(event) => setConfirmPassword(event.target.value)}
              required
              autoComplete="new-password"
            />

            <Button type="submit" fullWidth loading={loading} className="h-12">
              Reset password
            </Button>
          </form>

          <p className="text-text-secondary mt-6 text-center text-sm">
            Back to{' '}
            <Link
              to="/login"
              className="text-accent hover:text-accent-light font-medium transition-colors"
            >
              sign in
            </Link>
          </p>
        </div>
      </div>

      <button
        type="button"
        onClick={() => setConnectionsOpen(true)}
        className="rf-control fixed bottom-5 right-5 z-20 flex h-12 w-12 items-center justify-center rounded-full text-[rgb(var(--rf-text-primary))] shadow-[0_18px_42px_rgba(var(--rf-shadow-color),0.18)]"
        title="Server settings"
        aria-label="Server settings"
      >
        <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={1.8}
            d="M10.325 4.317a1.724 1.724 0 013.35 0 1.724 1.724 0 002.573 1.066 1.724 1.724 0 012.898 1.675 1.724 1.724 0 001.066 2.573 1.724 1.724 0 010 3.35 1.724 1.724 0 00-1.066 2.573 1.724 1.724 0 01-2.898 1.675 1.724 1.724 0 00-2.573 1.066 1.724 1.724 0 01-3.35 0 1.724 1.724 0 00-2.573-1.066 1.724 1.724 0 01-2.898-1.675 1.724 1.724 0 00-1.066-2.573 1.724 1.724 0 010-3.35 1.724 1.724 0 001.066-2.573 1.724 1.724 0 012.898-1.675 1.724 1.724 0 002.573-1.066z"
          />
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={1.8}
            d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
          />
        </svg>
      </button>

      <ServerConnectionModal open={connectionsOpen} onClose={() => setConnectionsOpen(false)} />
    </div>
  );
}
